[PHP]
; 基础优化
memory_limit = 512M
upload_max_filesize = 1024M
post_max_size = 1024M
max_execution_time = 3000
date.timezone = Asia/Shanghai

; 禁用错误日志到文件
display_errors = Off
log_errors = On
error_log = /dev/null

; Opcache 优化 (非常重要)
opcache.enable=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.revalidate_freq=2
opcache.enable_cli=1
