server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    # 禁用所有日志以避免在容器内生成日志文件
    access_log off;
    error_log /dev/null;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
