[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000

; 优化进程管理方式
; dynamic 或 static 是生产环境常见选择。
; 对于内存有限的容器，dynamic 比较灵活。
pm = dynamic
pm.max_children = 50
pm.start_servers = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 15
pm.max_requests = 500

; 禁用慢日志以避免生成文件
slowlog = /dev/null
request_slowlog_timeout = 0

; 允许的环境变量
clear_env = no

; 捕获输出
catch_workers_output = yes
decorate_workers_output = no
